language: node_js

install:
  - npm install -g bower
  - npm install -g gulp
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_script:
  - npm install
  - bower install

script: return 0

before_deploy: make release

deploy:
  provider: s3
  access_key_id: AKIAIKAOQMWIKVZMP4BQ
  secret_access_key:
    secure: bSFJIUo7mbk6e0YYS9SrppgZ+vL22nvpw8UHaP5CVa6mf1p0jjmzW2qOJGMX2+uI0zOL9ElzF8i88wDleD6TEw+bCw+H9YrSPkffVBbKOyyKX5ipmlOdbezQf/ot4ovgAJCxahoUy4JHUoquhsiiZoRL7QbnOdJ6XHl88wF2Lsw=
  bucket: com.rhokthehood.www
  skip_cleanup: true
  local-dir: release
  acl: public_read
  on:
    repo: citruspi/RHoKTheHood
