install:
  - npm install -g bower
  - npm install -g gulp
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_script:
  - npm install
  - bower install

language: node_js
script: return 0

before_deploy: make release
deploy:
  provider: s3
  access_key_id: AKIAIKAOQMWIKVZMP4BQ
  secret_access_key:
    secure: bq6uMPVbDjQrepMrxTfJHHvMJr9fZVLkTjVnVf6w/JfxFzYof7o8POemTkfIfqHt+/E38YnPnP4YVUO8iEdP8yo1AfDGi4PtzEC4LUyP/p9gMFStnhy8Alp3t+xu1gF5SQOVSIuVT21RDyH18qE4gAEiVKAsnx62DEbeHPi2+Ec=
  bucket: com.rhokthehood.www
  skip_cleanup: true
  local-dir: release
  acl: public_read
  on:
    repo: citruspi/RHoKTheHood
